# To update the environment use:
# conda env update --file environment.yml --prune
name: germeval2022
channels:
  - pytorch
  - huggingface
  - defaults
dependencies:
  - python=3.8
  - git
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - cudatoolkit
  - pytorch
  - torchvision
  - torchaudio
  - tensorflow
  - keras
  - tensorflow-gpu
  - jupyter # jupyter
  - ipython # jupyter
  - pylint # jupyter
  - invoke # jupyter
  - ipywidgets # jupyter
  - pip:
    - transformers
    - tbparse
    - git+https://github.com/andreasvc/readability
    - syntok
    - stanza
    - textcomplexity
